Algoritmo "semnome"


var
num : vetor[1..3, 1..3] de inteiro
l, c : inteiro

inicio
  para l de 1 ate 3 faca
     para c de 1 ate 3 faca
        escreva("Digite um valor para a posição [",l , "," , c, "] : ")
        leia(num[l,c])
     fimpara
  fimpara

  para l de 1 ate 3 faca
      para c de 1 ate 3 faca
           escreva(num[l,c])
       fimpara
           escreval
           
  fimpara
fimalgoritmo